### ISSUE TITLE
rename js-for-apache-dubbo to dubbo-js

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo-js#109]
In readme, js-for-apache-dubbo change be change to dubbo-js?

**Comment by hufeng** [comment]
@ralf0131 +1 We should finalize the name as soon as possible. 

 This also involves the name of the NPM module

**Comment by hufeng** [comment]
@ralf0131 How is it going?

**Comment by hufeng** [comment]
@ralf0131 rename js-for-apache-dubbo to dubbo-js, except npm module name.

**Comment by ralf0131** [comment]
@hufeng Can you send a pull request to fix it?
